### ISSUE TITLE
How to run this on stand-alone GPU cluster

### ISSUE THREAD

**Issue by amitchandak** [microsoft/Stochastic-Mixture-of-Experts#1]
Hi,
I am student and trying to run you code. 
I am unable to run the code after following your instructions.
I have installed "fairseq" repo inside the folder of your code-repo.
I  followed the steps and able to run the preporocess step.
When I try to train model  "run_iwslt14_de_en.sh", first I got the error :
"/Stochastic-Mixture-of-Experts/thor/transformer_thor_layer.py", line 21, in <module>
    class ThorTransformerEncoderLayer(TransformerEncoderLayer):"
It was unable to find "TransformerEncoderLayer" class/method. 
When I checked the corresponding package "/fairseq/models/transformer/" , there is no such class. Looks like they have renamed it to "TransformerEncoder" .  Correspondingly I  made the following changes in "transformer_thor_layer.py"

#from fairseq.models.transformer import TransformerDecoderLayer, TransformerEncoderLayer
from fairseq.models.transformer.transformer_decoder import TransformerDecoder
from fairseq.models.transformer.transformer_encoder import TransformerEncoder

But now I get a new error:

/Stochastic-Mixture-of-Experts/thor/transformer_thor_layer.py", line 40, in __init__
    super().__init__(args)
TypeError: __init__() missing 2 required positional arguments: 'dictionary' and 'embed_tokens

Can you please help with this ? Thank you.
Thank you,
Amit

**Comment by amitchandak** [comment]
I am able to run it now, the files have been moved to module's folder.

**Comment by daeunni** [comment]
@amitchandak  Hi, where did u find `train.py` file used in run.sh ?
